from pathlib import Path

from nextyle.cssProperty import css_Property


HEADER = '''"""
Type stubs for nextyle.select.

Auto-generated from cssProperty.py.
Do not edit this file manually.
Edit nextyleBuilder.py and run it again.
"""

from typing import Any, Dict, Optional, Tuple, TYPE_CHECKING


if TYPE_CHECKING:
    from .nextyle import Nextyle


RuleKey = Tuple[str, str]


class Select:
    selector_name: str
    parent: "Nextyle"
    pseudo_suffix: str
    rules: Dict[RuleKey, Dict[str, str]]

    def __init__(
        self,
        selector_name: str,
        parent_nextyle: "Nextyle",
        pseudo_suffix: str = "",
        rules: Optional[Dict[RuleKey, Dict[str, str]]] = None,
    ) -> None: ...

    def _add_prop(
        self,
        css_prop: str,
        base_val: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    @staticmethod
    def _make_css_method(
        css_property_name: str,
    ) -> Any: ...

    def __getattr__(self, name: str) -> Any: ...

    # --------------------------------------------------------
    # Pseudo API
    # --------------------------------------------------------

    def pseudo(
        self,
        pseudo_name: str,
    ) -> "Select": ...

    # Pseudo-class shortcuts

    def hover(self) -> "Select": ...
    def focus(self) -> "Select": ...
    def focus_visible(self) -> "Select": ...
    def focus_within(self) -> "Select": ...
    def active(self) -> "Select": ...
    def disabled(self) -> "Select": ...
    def enabled(self) -> "Select": ...
    def checked(self) -> "Select": ...
    def visited(self) -> "Select": ...

    def first_child(self) -> "Select": ...
    def last_child(self) -> "Select": ...
    def first_of_type(self) -> "Select": ...
    def last_of_type(self) -> "Select": ...

    # Pseudo-element shortcuts

    def before(self) -> "Select": ...
    def after(self) -> "Select": ...
    def placeholder(self) -> "Select": ...
    def selection(self) -> "Select": ...
    def marker(self) -> "Select": ...

    # --------------------------------------------------------
    # Renderer API
    # --------------------------------------------------------

    def render_group(
        self,
        group_name: str,
    ) -> Optional[str]: ...
'''


def build_select_methods() -> list[str]:
    """
    CSS propertyهای css_Property را به methodهای type stub تبدیل می‌کند.

    نمونهٔ خروجی:

        def background_color(
            self,
            value: Optional[Any] = None,
            **kwargs: Any,
        ) -> "Select": ...

    `kwargs` برای breakpointها است:

        x.select(".box").color(
            "red",
            sm="blue",
            md="green",
        )
    """
    methods: list[str] = []

    for css_property in css_Property:
        method_name = css_property.replace("-", "_")

        methods.append(
            f'''    def {method_name}(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...'''
        )

    return methods


dynamic_methods = build_select_methods()

stub_content = (
    HEADER
    + "\n\n"
    + "\n\n".join(dynamic_methods)
    + "\n"
)



package_dir = Path(__file__).resolve().parent

output_path = package_dir / "select.pyi"

output_path.write_text(
    stub_content,
    encoding="utf-8",
)

print("Select stub generated successfully:")
print(f"  {output_path}")
print(f"  Dynamic CSS methods: {len(dynamic_methods)}")
