from pathlib import Path

from nextyle.cssProperty import css_Property


HEADER = '''from typing import Any, Dict, Optional, Tuple, TYPE_CHECKING

if TYPE_CHECKING:
    from .nextyle import Nextyle


RuleKey = Tuple[str, str]


class Select:
    selector_name: str
    parent: "Nextyle"
    pseudo_suffix: str
    scope_selector: str
    rules: Dict[RuleKey, Dict[str, str]]

    def __init__(self, selector_name: str, parent_nextyle: "Nextyle", pseudo_suffix: str = "", rules: Optional[Dict[RuleKey, Dict[str, str]]] = None, scope_selector: str = "") -> None: ...
    def _add_prop(self, css_prop: str, base_val: Optional[Any] = None, **kwargs: Any) -> "Select": ...
    @staticmethod
    def _make_css_method(css_property_name: str) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def pseudo(self, pseudo_name: str) -> "Select": ...
    def hover(self) -> "Select": ...
    def focus(self) -> "Select": ...
    def focus_visible(self) -> "Select": ...
    def focus_within(self) -> "Select": ...
    def active(self) -> "Select": ...
    def disabled(self) -> "Select": ...
    def enabled(self) -> "Select": ...
    def checked(self) -> "Select": ...
    def visited(self) -> "Select": ...
    def first_child(self) -> "Select": ...
    def last_child(self) -> "Select": ...
    def first_of_type(self) -> "Select": ...
    def last_of_type(self) -> "Select": ...
    def before(self) -> "Select": ...
    def after(self) -> "Select": ...
    def placeholder(self) -> "Select": ...
    def selection(self) -> "Select": ...
    def marker(self) -> "Select": ...
    def _render_selector(self, pseudo_suffix: str) -> str: ...
    def render_group(self, group_name: str) -> Optional[str]: ...
'''


def build_select_methods() -> list[str]:
    return [f'    def {css_property.replace("-", "_")}(self, value: Optional[Any] = None, **kwargs: Any) -> "Select": ...' for css_property in css_Property]


stub_content = HEADER + "\n" + "\n".join(build_select_methods()) + "\n"

package_dir = Path(__file__).resolve().parent
output_path = package_dir / "select.pyi"
output_path.write_text(stub_content, encoding="utf-8")

print(f"Select stub generated successfully: {output_path}")
print(f"Dynamic CSS methods: {len(css_Property)}")
