"""
Type stubs for nextyle.select.

Auto-generated from cssProperty.py.
Do not edit this file manually.
Edit nextyleBuilder.py and run it again.
"""

from typing import Any, Dict, Optional, Tuple, TYPE_CHECKING


if TYPE_CHECKING:
    from .nextyle import Nextyle


RuleKey = Tuple[str, str]


class Select:
    selector_name: str
    parent: "Nextyle"
    pseudo_suffix: str
    rules: Dict[RuleKey, Dict[str, str]]

    def __init__(
        self,
        selector_name: str,
        parent_nextyle: "Nextyle",
        pseudo_suffix: str = "",
        rules: Optional[Dict[RuleKey, Dict[str, str]]] = None,
    ) -> None: ...

    def _add_prop(
        self,
        css_prop: str,
        base_val: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    @staticmethod
    def _make_css_method(
        css_property_name: str,
    ) -> Any: ...

    def __getattr__(self, name: str) -> Any: ...

    # --------------------------------------------------------
    # Pseudo API
    # --------------------------------------------------------

    def pseudo(
        self,
        pseudo_name: str,
    ) -> "Select": ...

    # Pseudo-class shortcuts

    def hover(self) -> "Select": ...
    def focus(self) -> "Select": ...
    def focus_visible(self) -> "Select": ...
    def focus_within(self) -> "Select": ...
    def active(self) -> "Select": ...
    def disabled(self) -> "Select": ...
    def enabled(self) -> "Select": ...
    def checked(self) -> "Select": ...
    def visited(self) -> "Select": ...

    def first_child(self) -> "Select": ...
    def last_child(self) -> "Select": ...
    def first_of_type(self) -> "Select": ...
    def last_of_type(self) -> "Select": ...

    # Pseudo-element shortcuts

    def before(self) -> "Select": ...
    def after(self) -> "Select": ...
    def placeholder(self) -> "Select": ...
    def selection(self) -> "Select": ...
    def marker(self) -> "Select": ...

    # --------------------------------------------------------
    # Renderer API
    # --------------------------------------------------------

    def render_group(
        self,
        group_name: str,
    ) -> Optional[str]: ...


    def accent_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def align_content(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def align_items(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def align_self(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def all(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_delay(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_direction(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_duration(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_fill_mode(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_iteration_count(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_name(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_play_state(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def animation_timing_function(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def aspect_ratio(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def backdrop_filter(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def backface_visibility(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_attachment(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_blend_mode(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_clip(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_image(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_origin(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_position_x(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_position_y(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_repeat(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def background_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def block_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_end_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_end_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_end_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_start_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_start_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_start_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_block_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_bottom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_bottom_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_bottom_left_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_bottom_right_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_bottom_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_bottom_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_collapse(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_end_end_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_end_start_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_image(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_image_outset(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_image_repeat(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_image_slice(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_image_source(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_image_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_end_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_end_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_end_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_start_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_start_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_start_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_inline_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_left(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_left_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_left_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_left_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_right(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_right_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_right_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_right_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_spacing(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_start_end_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_start_start_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_top(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_top_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_top_left_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_top_right_radius(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_top_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_top_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def border_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def bottom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def box_decoration_break(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def box_shadow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def box_sizing(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def break_after(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def break_before(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def break_inside(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def caption_side(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def caret_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def clear(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def clip(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def clip_path(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def color_scheme(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_count(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_fill(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_gap(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_rule(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_rule_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_rule_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_rule_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_span(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def column_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def columns(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def content(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def counter_increment(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def counter_reset(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def counter_set(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def cursor(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def direction(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def display(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def empty_cells(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def filter(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex_basis(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex_direction(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex_flow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex_grow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex_shrink(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def flex_wrap(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def float(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_family(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_feature_settings(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_kerning(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_size_adjust(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_stretch(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_variant(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_variant_caps(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def font_weight(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def gap(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_area(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_auto_columns(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_auto_flow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_auto_rows(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_column(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_column_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_column_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_row(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_row_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_row_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_template(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_template_areas(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_template_columns(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def grid_template_rows(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def hanging_punctuation(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def height(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def hyphens(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def hyphenate_character(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def image_rendering(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def initial_letter(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inline_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset_block_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset_block_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset_inline_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def inset_inline_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def isolation(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def justify_content(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def justify_items(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def justify_self(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def left(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def letter_spacing(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def line_height(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def list_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def list_style_image(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def list_style_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def list_style_type(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_block_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_block_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_bottom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_inline_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_inline_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_left(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_right(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def margin_top(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def marker(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def marker_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def marker_mid(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def marker_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_clip(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_composite(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_image(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_mode(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_origin(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_repeat(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mask_type(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def max_block_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def max_height(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def max_inline_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def max_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def min_block_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def min_inline_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def min_height(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def min_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def mix_blend_mode(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def object_fit(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def object_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def offset(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def offset_anchor(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def offset_distance(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def offset_path(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def offset_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def offset_rotate(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def opacity(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def order(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def orphans(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def outline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def outline_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def outline_offset(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def outline_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def outline_width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overflow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overflow_anchor(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overflow_wrap(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overflow_x(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overflow_y(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overscroll_behavior(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overscroll_behavior_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overscroll_behavior_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overscroll_behavior_x(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def overscroll_behavior_y(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_block_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_block_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_bottom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_inline_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_inline_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_left(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_right(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def padding_top(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def page_break_after(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def page_break_before(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def page_break_inside(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def paint_order(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def perspective(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def perspective_origin(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def place_content(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def place_items(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def place_self(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def pointer_events(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def quotes(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def resize(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def right(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def rotate(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def row_gap(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scale(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_behavior(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_block_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_block_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_bottom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_inline_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_inline_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_left(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_right(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_margin_top(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_block(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_block_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_block_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_bottom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_inline(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_inline_end(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_inline_start(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_left(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_right(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_padding_top(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_snap_align(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_snap_stop(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scroll_snap_type(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def scrollbar_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def shape_outside(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def tab_size(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def table_layout(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_align(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_align_last(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_decoration(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_decoration_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_decoration_line(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_decoration_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_decoration_thickness(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_emphasis(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_emphasis_color(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_emphasis_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_emphasis_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_indent(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_justify(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_orientation(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_overflow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_shadow(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_transform(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_underline_offset(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def text_underline_position(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def top(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transform(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transform_origin(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transform_style(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transition(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transition_delay(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transition_duration(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transition_property(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def transition_timing_function(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def translate(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def unicode_bidi(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def user_select(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def vertical_align(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def visibility(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def white_space(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def widows(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def width(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def word_break(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def word_spacing(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def word_wrap(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def writing_mode(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def z_index(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...

    def zoom(
        self,
        value: Optional[Any] = None,
        **kwargs: Any,
    ) -> "Select": ...
