
from __future__ import annotations
from typing import Any, Optional

from .tagBuilder import TagBuilder, RawHTML

class ElementBuilder:
    elementsContainer: TagBuilder


    def __init__(self) -> None: ...

    def element(self,tagName: str = "NoName",text: Any = "",selfClose: bool = False,props: Any = "",parent: Optional[TagBuilder] = None,**attributes: Any) -> TagBuilder: ...
    def raw(self, html: str, parent: Optional[TagBuilder] = None) -> RawHTML: ...


    def html(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def head(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def body(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def title(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def style(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def address(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def article(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def aside(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def footer(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def header(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def h1(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def h2(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def h3(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def h4(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def h5(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def h6(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def hgroup(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def main(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def nav(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def section(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def blockquote(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def dd(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def div(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def dl(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def dt(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def figcaption(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def figure(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def li(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def menu(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def ol(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def p(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def pre(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def ul(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def a(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def abbr(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def b(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def bdi(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def bdo(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def cite(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def code(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def data(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def dfn(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def em(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def i(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def kbd(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def mark(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def q(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def rp(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def rt(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def ruby(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def s(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def samp(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def small(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def span(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def strong(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def sub(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def sup(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def time(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def u(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def var(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def audio(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def canvas(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def video(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def iframe(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def object(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def picture(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def script(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def noscript(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def caption(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def colgroup(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def table(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def tbody(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def td(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def tfoot(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def th(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def thead(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def tr(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def button(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def datalist(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def fieldset(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def form(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def label(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def legend(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def meter(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def optgroup(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def option(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def output(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def progress(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def select(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def textarea(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def details(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def dialog(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def summary(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def ins(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def area(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def base(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def br(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def col(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def embed(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def hr(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def img(self, src="", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def input(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def link(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def meta(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def param(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def source(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def track(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...
    def wbr(self, text: Any = "", props: Any = "", parent: Optional[TagBuilder] = None, **attributes: Any) -> TagBuilder: ...